export const categories = [
  "Pendampingan Skripsi",
  "Olah Data (Bimbingan)",
  "Metodologi & Bab 1–3",
  "Revisi & Proofreading",
  "PPT Sidang",
  "Sitasi & Mendeley",
  "Turnitin Coaching",
  "Coding & Tools",
];

export const gigs = [
  {
    id: "1",
    title: "Pendampingan Skripsi 1:1 (Roadmap + Target Mingguan)",
    category: "Pendampingan Skripsi",
    priceFrom: 250_000,
    rating: "4.9",
    sold: 180,
    seller: {
      id: "1",
      name: "Sinta",
      title: "Academic Mentor",
      level: "Top Rated",
    },
  },
  {
    id: "2",
    title: "Olah Data SPSS / Excel (Dibimbing + Interpretasi)",
    category: "Olah Data (Bimbingan)",
    priceFrom: 300_000,
    rating: "4.8",
    sold: 140,
    seller: { id: "2", name: "Dimas", title: "Data Analyst", level: "Pro" },
  },
  {
    id: "3",
    title: "Review Metodologi: Variabel, Instrumen, Teknik Analisis",
    category: "Metodologi & Bab 1–3",
    priceFrom: 200_000,
    rating: "4.8",
    sold: 95,
    seller: { id: "3", name: "Raka", title: "Research Coach", level: "Pro" },
  },
  {
    id: "4",
    title: "Revisi Bab 1–3 sesuai Catatan Dosen (Bukan dibuatkan)",
    category: "Revisi & Proofreading",
    priceFrom: 180_000,
    rating: "4.7",
    sold: 210,
    seller: {
      id: "4",
      name: "Nadia",
      title: "Editor & Proofreader",
      level: "Fast Response",
    },
  },
  {
    id: "5",
    title: "PPT Sidang: Storyline + Desain Profesional (Figma/PowerPoint)",
    category: "PPT Sidang",
    priceFrom: 220_000,
    rating: "4.9",
    sold: 160,
    seller: {
      id: "1",
      name: "Sinta",
      title: "Academic Mentor",
      level: "Top Rated",
    },
  },
  {
    id: "6",
    title: "Rapikan Sitasi Mendeley/Zotero + Format Daftar Pustaka",
    category: "Sitasi & Mendeley",
    priceFrom: 150_000,
    rating: "4.8",
    sold: 120,
    seller: {
      id: "4",
      name: "Nadia",
      title: "Editor & Proofreader",
      level: "Fast Response",
    },
  },
  {
    id: "7",
    title: "Turnitin Coaching: Parafrase Etis + Struktur Ulang (Edukasi)",
    category: "Turnitin Coaching",
    priceFrom: 200_000,
    rating: "4.7",
    sold: 110,
    seller: { id: "3", name: "Raka", title: "Research Coach", level: "Pro" },
  },
  {
    id: "8",
    title: "Mentoring Coding: Laravel/Next.js untuk Skripsi (1–2 jam)",
    category: "Coding & Tools",
    priceFrom: 350_000,
    rating: "4.9",
    sold: 80,
    seller: { id: "2", name: "Dimas", title: "Data Analyst", level: "Pro" },
  },
];

export const freelancers = [
  {
    id: "1",
    name: "Sinta",
    title: "Academic Mentor • Struktur & Timeline Skripsi",
    rating: "4.9",
    jobs: 520,
    badges: ["Top Rated", "Fast Response"],
    skills: ["Roadmap", "Outline", "PPT", "Coaching"],
  },
  {
    id: "2",
    name: "Dimas",
    title: "Data Analyst • SPSS/Excel/Python (Bimbingan)",
    rating: "4.8",
    jobs: 410,
    badges: ["Pro"],
    skills: ["SPSS", "Excel", "Statistik", "Interpretasi"],
  },
  {
    id: "3",
    name: "Raka",
    title: "Research Coach • Metodologi & Bab 1–3",
    rating: "4.8",
    jobs: 360,
    badges: ["Pro"],
    skills: ["Metodologi", "Instrumen", "Analisis", "Turnitin Coaching"],
  },
  {
    id: "4",
    name: "Nadia",
    title: "Editor • Proofreading & Format Akademik",
    rating: "4.7",
    jobs: 690,
    badges: ["Fast Response"],
    skills: ["Proofreading", "Ejaan", "Sitasi", "Format"],
  },
];
